// import strukdat.Graph;

class MyVertex {
    // Deklarasi variabel instance untuk menyimpan nama node
    String nodeName;

    // Konstruktor untuk menginisialisasi nodeName dengan nilai yang diberikan
    MyVertex(String name) {
        this.nodeName = name;
    }

    // Override metode toString untuk mengembalikan representasi string dari objek MyVertex
    @Override
    public String toString() {
        return nodeName; // Mengembalikan nama node
    }
}

public class MainProgram {
    public static void main(String[] args) {

        //create vertex
        MyVertex PikAvenue = new MyVertex("PIK Avenue");
        MyVertex RsPik = new MyVertex("RS PIK");
        MyVertex GreenSedayu = new MyVertex("Green Sedayu");
        MyVertex UnivBinaSarana = new MyVertex("Universitas Bina Sarana");
        MyVertex RamayanaCengkareng = new MyVertex("Ramayana Cengkareng");
        MyVertex ItPln = new MyVertex("Institut Teknologi PLN");
        MyVertex PuriIndahMall = new MyVertex("Puri Indah Mall");
        MyVertex RsudKembangan = new MyVertex("RSUD Kembangan");
        MyVertex UnivMercuBuana = new MyVertex("Universitas Mercu Buana");
        MyVertex UnivBudiLuhur = new MyVertex("Universitas Budi Luhur");
        MyVertex SiloamHospitalSimatupang = new MyVertex("Siloam Hospital Simatupang");
        MyVertex CiladakTownSquare = new MyVertex("Ciladak Town Square");
        MyVertex TransmartCiladak = new MyVertex("Transmart Ciladak");
        MyVertex AeonMall = new MyVertex("AEON Mall");
        MyVertex UnivPancasila = new MyVertex("Universitas Pancasila");
        MyVertex RsBinawaluya = new MyVertex("RS Binawaluya");
        MyVertex RsAdhyaksa = new MyVertex("RS Adhyaksa");
        MyVertex LippoPlazaKeramatJati = new MyVertex("LIPPO Plaza Keramat Jati");
        MyVertex RsBhayangkara = new MyVertex("RS Bhayangkara");
        MyVertex UnivDirgantara = new MyVertex("Universitas Dirgantara");
        MyVertex RsAngkatanUdara = new MyVertex("RS Angkatan Udara");
        MyVertex UnivKristenIndonesai = new MyVertex("Universitas Kristen Indonesia");
        MyVertex UnivBorobudur = new MyVertex("Universitas Borobudur");
        MyVertex UnivNusaMandiri = new MyVertex("Universitas Nusa Mandiri");
        MyVertex PondokKelapaTownSquare = new MyVertex("Pondok Kelapa Town Square");
        MyVertex MallCipinangJakarta = new MyVertex("Mall Cipinang Jakarta");
        MyVertex MallBasura = new MyVertex("Mall Basura");
        MyVertex UnivMputantular = new MyVertex("Universitas Mputantular");
        MyVertex RsPusatPersahabatan = new MyVertex("RS Pusat Persahabatan");
        MyVertex ArionMall = new MyVertex("Arion Mall");
        MyVertex UnivNegeriJakarta = new MyVertex("Universitas Negeri Jakarta");
        MyVertex StmaTrisakti = new MyVertex("STMA Trisakti");
        MyVertex UnivJakarta = new MyVertex("Universitas Jakarta");
        MyVertex RsCempakaPutih = new MyVertex("RS Cempaka Putih");
        MyVertex InstitutMultimediaAsmi = new MyVertex("Institut Multimedia Asmi");
        MyVertex MallKelapaGadin = new MyVertex("Mall Kelapa Gading");
        MyVertex MallArtaGading = new MyVertex("Mall Arta Gading");
        MyVertex RsIslamSukapura = new MyVertex("RS Islam Sukapura");
        MyVertex PoliteknikLP3IJakut = new MyVertex("Politeknik LP3I Jakarta Utara");
        MyVertex RsPelabuhan = new MyVertex("RS Pelabuhan");
        MyVertex RsudCilincing = new MyVertex("RSUD Cilincing");
        MyVertex UnivPertiwi = new MyVertex("Universitas Pertiwi");
        MyVertex RsudKoja = new MyVertex("RSUD Koja");
        MyVertex SitkesDrSismadi = new MyVertex("SITKES DR.Sismadi");
        MyVertex Univ17Agustus = new MyVertex("Universitas 17 Agustus");
        MyVertex SunterMall = new MyVertex("Sunter Mall");
        MyVertex RsPademangan = new MyVertex("RS Pademangan");
        MyVertex WtcMangga2 = new MyVertex("WTC Mangga 2");
        MyVertex UnivBundaMulia = new MyVertex("Universitas Bunda Mulia");
        MyVertex UnivKedokteranAtmaJaya = new MyVertex("Universitas Kedokteran Atma Jaya");
        MyVertex PluitEmporium = new MyVertex("Pluit Emporium");
        MyVertex PluitVillage = new MyVertex("Pluit Village");
        MyVertex SeasonCity = new MyVertex("Season City");
        MyVertex MallCiputra = new MyVertex("Mall Ciputra");
        MyVertex UnivTrisakti = new MyVertex("Universitas Trisakti");
        MyVertex RsSumberWaras = new MyVertex("RS Sumber Waras");
        MyVertex ItcRoxyMas = new MyVertex("ITC Roxy Mas");
        MyVertex UnivDianNusantara = new MyVertex("Universitas Dian Nusantar");
        MyVertex UnivPodomoro = new MyVertex("Universitas Podomoro");
        MyVertex MallTamanAnggrek = new MyVertex("Mall Taman Anggrek");
        MyVertex UnivEsaUnggul = new MyVertex("Universitas Esa Unggul");
        MyVertex RsSiloamKebonJeruk = new MyVertex("RS Siloam Kebon Jeruk");
        MyVertex UnivBinus = new MyVertex("Universitas Binus");
        MyVertex RsHarapanKita = new MyVertex("RS Harapan Kita");
        MyVertex RsPelni = new MyVertex("RS Pelni");
        MyVertex UnivPertamina = new MyVertex("Unversitas Pertamina");
        MyVertex UnivDarunnajah = new MyVertex("Universitas Darunnajah");
        MyVertex AlAzhar = new MyVertex("Al-Azhar");
        MyVertex GandariaCity = new MyVertex("Gandaria City");
        MyVertex UnivDrHamka = new MyVertex("Universitas Dr. Hamka");
        MyVertex BlokMPlaza = new MyVertex("Blok M Plaza");
        MyVertex PondokIndah = new MyVertex("Pondok Indah");
        MyVertex RsPondokIndah = new MyVertex("RS Pondok Indah");
        MyVertex LippoMallKemang = new MyVertex("Lippo Mall Kemang");
        MyVertex PlazaAdorama = new MyVertex("Plaza Adorama");
        MyVertex UnivMhThamrin = new MyVertex("Universitas MH Thamrin");
        MyVertex RsTriaDipa = new MyVertex("RS Tria Dipa");
        MyVertex UnivTrilogi = new MyVertex("Universitas Trilogi");
        MyVertex RsTibet = new MyVertex("RS Tibet");
        MyVertex PlazaKalibata = new MyVertex("Plaza Kalibata");
        MyVertex UnivLia = new MyVertex("Universitas LIA");
        MyVertex UnivBinawan = new MyVertex("Universitas Binawan");
        MyVertex RsTniDrMintohardjo = new MyVertex("RS TNI Dr. Minthohardjo");
        MyVertex PasificPlace = new MyVertex("Pasific Place");
        MyVertex UnivAtmaJaya = new MyVertex("Universitas Atma Jaya");
        MyVertex LotteMall = new MyVertex("Lotte Mall");
        MyVertex Kuningan = new MyVertex("Kuningan");
        MyVertex FPsikologUnj = new MyVertex("Fakultas Psikolog UNJ");
        MyVertex Kasablanka = new MyVertex("Kasablanka");
        MyVertex RsAgung = new MyVertex("RS Agung");
        MyVertex UnivNahdlatulUlama = new MyVertex("Unversitas Nahdlatul Ulama");
        MyVertex GrandIndonesia = new MyVertex("Grand Indonesia");
        MyVertex Sarina = new MyVertex("Sarina");
        MyVertex UnivBungKarno = new MyVertex("Universitas Bung Karno");
        MyVertex UnivPersadaYai = new MyVertex("Universitas Persada YAI");
        MyVertex GajahMadaPlaza = new MyVertex("Gajah Mada Place");
        MyVertex PlazaAtrium = new MyVertex("Plaza Atrium");
        MyVertex GlodokPlaza = new MyVertex("Glodok Plaza");
        MyVertex RsHusada = new MyVertex("RS Husada");
        MyVertex Mangga2Square = new MyVertex("Mangga 2 Square");
        MyVertex PlazaBuaran = new MyVertex("Plaza Buaran");
        MyVertex RsIslamJakarta = new MyVertex("RS Islam Jakarta");
        MyVertex KepulauanSeribu = new MyVertex("Kepulauan Seribu");

        WeightedGraph<MyVertex> WG = new WeightedGraph<MyVertex>(true); //directed
        WG.addEdge(PikAvenue, RsPik, 1.7);
        WG.addEdge(RsPik, PikAvenue, 2.9);
        WG.addEdge(RsPik, PluitEmporium, 9);
        WG.addEdge(PluitEmporium, RsPik, 7.2);
        WG.addEdge(RsPik, GreenSedayu, 7.8);
        WG.addEdge(GreenSedayu, RsPik, 6.4);
        WG.addEdge(PluitEmporium, PluitVillage, 1.3);
        WG.addEdge(PluitVillage, PluitEmporium, 3.5);
        WG.addEdge(GreenSedayu, UnivBinaSarana, 3.3);
        WG.addEdge(UnivBinaSarana, GreenSedayu, 1.2);
        WG.addEdge(PluitEmporium, UnivKedokteranAtmaJaya, 0.6);
        WG.addEdge(UnivKedokteranAtmaJaya, PluitEmporium, 0.6);
        WG.addEdge(UnivBinaSarana, RamayanaCengkareng, 1.7);
        WG.addEdge(RamayanaCengkareng, UnivBinaSarana, 1.7);
        WG.addEdge(UnivKedokteranAtmaJaya, UnivBundaMulia, 3.3);
        WG.addEdge(UnivBundaMulia, UnivKedokteranAtmaJaya, 3.3);
        WG.addEdge(PluitEmporium, SeasonCity, 3.8);
        WG.addEdge(SeasonCity, PluitEmporium, 3.5);
        WG.addEdge(SeasonCity, UnivKedokteranAtmaJaya, 4.3);
        WG.addEdge(UnivKedokteranAtmaJaya, SeasonCity, 3.6);
        WG.addEdge(UnivBundaMulia, WtcMangga2, 3.3);
        WG.addEdge(WtcMangga2, UnivBundaMulia, 1.9);
        WG.addEdge(WtcMangga2, Univ17Agustus, 6.9);
        WG.addEdge(Univ17Agustus, WtcMangga2, 5.9);
        WG.addEdge(Univ17Agustus, RsPademangan, 3.3);
        WG.addEdge(RsPademangan, Univ17Agustus, 5.2);
        WG.addEdge(RsPademangan, WtcMangga2, 2.3);
        WG.addEdge(WtcMangga2, RsPademangan, 1.1);
        WG.addEdge(WtcMangga2, Mangga2Square, 0.45);
        WG.addEdge(Mangga2Square, WtcMangga2, 0.45);
        WG.addEdge(Univ17Agustus, SitkesDrSismadi, 3.8);
        WG.addEdge(SitkesDrSismadi, Univ17Agustus, 3.8);
        WG.addEdge(SitkesDrSismadi, SunterMall, 3.9);
        WG.addEdge(SunterMall, SitkesDrSismadi, 4.0);
        WG.addEdge(SunterMall, Univ17Agustus, 1.6);
        WG.addEdge(Univ17Agustus, SunterMall, 2.2);
        WG.addEdge(SitkesDrSismadi, RsudKoja, 3);
        WG.addEdge(RsudKoja, SitkesDrSismadi, 3.2);
        WG.addEdge(SitkesDrSismadi, PoliteknikLP3IJakut, 4.2);
        WG.addEdge(PoliteknikLP3IJakut, SitkesDrSismadi, 4.2);
        WG.addEdge(PoliteknikLP3IJakut, RsudKoja, 3);
        WG.addEdge(RsudKoja, PoliteknikLP3IJakut, 3.4);
        WG.addEdge(RsudKoja, UnivPertiwi, 2);
        WG.addEdge(UnivPertiwi, RsudKoja, 1.9);
        WG.addEdge(UnivPertiwi, RsudCilincing, 1.8);
        WG.addEdge(RsudCilincing, UnivPertiwi, 1.8);
        WG.addEdge(UnivPertiwi, RsPelabuhan, 1.7);
        WG.addEdge(RsPelabuhan, UnivPertiwi, 1.7);
        WG.addEdge(RsPelabuhan, PoliteknikLP3IJakut, 2.5);
        WG.addEdge(PoliteknikLP3IJakut, RsPelabuhan, 2.5);
        WG.addEdge(PoliteknikLP3IJakut, RsIslamSukapura, 3.6);
        WG.addEdge(RsIslamSukapura, PoliteknikLP3IJakut, 3.6);
        WG.addEdge(RsPelabuhan, RsIslamSukapura, 2.1);
        WG.addEdge(RsIslamSukapura, RsPelabuhan, 2.1);
        WG.addEdge(RsIslamSukapura, MallKelapaGadin, 3.6);
        WG.addEdge(MallKelapaGadin, RsIslamSukapura, 4.1);
        WG.addEdge(MallKelapaGadin, MallArtaGading, 3.0);
        WG.addEdge(MallArtaGading, MallKelapaGadin, 3.4);
        WG.addEdge(MallArtaGading, PoliteknikLP3IJakut, 4.5);
        WG.addEdge(PoliteknikLP3IJakut, MallArtaGading, 2.7);
        WG.addEdge(MallArtaGading, InstitutMultimediaAsmi, 4.7);
        WG.addEdge(InstitutMultimediaAsmi, MallArtaGading, 4.4);
        WG.addEdge(MallArtaGading, InstitutMultimediaAsmi, 4.3);
        WG.addEdge(InstitutMultimediaAsmi, MallArtaGading, 4.6);
        WG.addEdge(InstitutMultimediaAsmi, ArionMall, 3.7);
        WG.addEdge(ArionMall, InstitutMultimediaAsmi, 2.9);
        WG.addEdge(InstitutMultimediaAsmi, RsCempakaPutih, 2.4);
        WG.addEdge(RsCempakaPutih, InstitutMultimediaAsmi, 3.5);
        WG.addEdge(RsCempakaPutih, MallArtaGading, 5.6);
        WG.addEdge(MallArtaGading, RsCempakaPutih, 4.1);
        WG.addEdge(MallArtaGading, SunterMall, 4.3);
        WG.addEdge(SunterMall, MallArtaGading, 4.6);
        WG.addEdge(RsCempakaPutih, PlazaAtrium, 4.1);
        WG.addEdge(PlazaAtrium, RsCempakaPutih, 6.2);
        WG.addEdge(PlazaAtrium, RsHusada, 4.9);
        WG.addEdge(RsHusada, PlazaAtrium, 6.2);
        WG.addEdge(RsHusada, Mangga2Square, 1.9);
        WG.addEdge(Mangga2Square, RsHusada, 3.2);
        WG.addEdge(RsCempakaPutih, UnivJakarta, 4.3);
        WG.addEdge(UnivJakarta, RsCempakaPutih, 4.0);
        WG.addEdge(UnivJakarta, StmaTrisakti, 1.7);
        WG.addEdge(StmaTrisakti, UnivJakarta, 1.6);
        WG.addEdge(StmaTrisakti, UnivNegeriJakarta, 1.7);
        WG.addEdge(UnivNegeriJakarta, StmaTrisakti, 1.6);
        WG.addEdge(UnivNegeriJakarta, ArionMall, 1.7);
        WG.addEdge(ArionMall, UnivNegeriJakarta, 2.7);
        WG.addEdge(UnivNegeriJakarta, UnivNahdlatulUlama, 3.7);
        WG.addEdge(UnivNahdlatulUlama, UnivNegeriJakarta, 5.1);
        WG.addEdge(UnivNahdlatulUlama, UnivPersadaYai, 0.65);
        WG.addEdge(UnivPersadaYai, UnivNahdlatulUlama, 0.65);
        WG.addEdge(UnivPersadaYai, PlazaAtrium, 2.6);
        WG.addEdge(PlazaAtrium, UnivPersadaYai, 5.4);
        WG.addEdge(PlazaAtrium, Sarina, 5.3);
        WG.addEdge(Sarina, PlazaAtrium, 3.5);
        WG.addEdge(UnivNahdlatulUlama, GrandIndonesia, 4.3);
        WG.addEdge(GrandIndonesia, UnivNahdlatulUlama, 5.2);
        WG.addEdge(GrandIndonesia, UnivBungKarno, 4.1);
        WG.addEdge(UnivBungKarno, GrandIndonesia, 3.2);
        WG.addEdge(UnivBungKarno, UnivNahdlatulUlama, 2.0);
        WG.addEdge(UnivNahdlatulUlama, UnivBungKarno, 2.2);
        WG.addEdge(UnivBungKarno, UnivPersadaYai, 0.9);
        WG.addEdge(UnivPersadaYai, UnivBungKarno, 0.9);
        WG.addEdge(GrandIndonesia, Sarina, 2.3);
        WG.addEdge(Sarina, GrandIndonesia, 1.5);
        WG.addEdge(Sarina, GajahMadaPlaza, 4.2);
        WG.addEdge(GajahMadaPlaza, Sarina, 5.4);
        WG.addEdge(GajahMadaPlaza, PlazaAtrium, 6.9);
        WG.addEdge(PlazaAtrium, GajahMadaPlaza, 4.5);
        WG.addEdge(GajahMadaPlaza, GlodokPlaza, 2.5);
        WG.addEdge(GlodokPlaza, GajahMadaPlaza, 5);
        WG.addEdge(GlodokPlaza, Mangga2Square, 3.5);
        WG.addEdge(Mangga2Square, GlodokPlaza, 2.6);
        WG.addEdge(Sarina, ItcRoxyMas, 4.3);
        WG.addEdge(ItcRoxyMas, Sarina, 5.9);
        WG.addEdge(ItcRoxyMas, GajahMadaPlaza, 3.1);
        WG.addEdge(GajahMadaPlaza, ItcRoxyMas, 2.3);
        WG.addEdge(ItcRoxyMas, SeasonCity, 2.8);
        WG.addEdge(SeasonCity, ItcRoxyMas, 2.3);
        WG.addEdge(SeasonCity, GlodokPlaza, 4.7);
        WG.addEdge(GlodokPlaza, SeasonCity, 4.6);
        WG.addEdge(SeasonCity, MallCiputra, 3.0);
        WG.addEdge(MallCiputra, SeasonCity, 2.9);
        WG.addEdge(MallCiputra, UnivTrisakti, 0.7);
        WG.addEdge(UnivTrisakti, MallCiputra, 0.5);
        WG.addEdge(UnivTrisakti, RsSumberWaras, 3.4);
        WG.addEdge(RsSumberWaras, UnivTrisakti, 0.8);
        WG.addEdge(RsSumberWaras, ItcRoxyMas, 0.55);
        WG.addEdge(ItcRoxyMas, RsSumberWaras, 0.55);
        WG.addEdge(MallCiputra, RamayanaCengkareng, 7.8);
        WG.addEdge(RamayanaCengkareng, MallCiputra, 8.1);
        WG.addEdge(RamayanaCengkareng, ItPln, 3.1);
        WG.addEdge(ItPln, RamayanaCengkareng, 3.1);
        WG.addEdge(ItPln, PuriIndahMall, 5.2);
        WG.addEdge(PuriIndahMall, ItPln, 5);
        WG.addEdge(PuriIndahMall, RsSiloamKebonJeruk, 5.8);
        WG.addEdge(RsSiloamKebonJeruk, PuriIndahMall, 4.4);
        WG.addEdge(RsSiloamKebonJeruk, UnivEsaUnggul, 2.9);
        WG.addEdge(UnivEsaUnggul, RsSiloamKebonJeruk, 3.6);
        WG.addEdge(UnivEsaUnggul, UnivDianNusantara, 2.4);
        WG.addEdge(UnivDianNusantara, UnivEsaUnggul, 2.2);
        WG.addEdge(UnivDianNusantara, UnivPodomoro, 2.6);
        WG.addEdge(UnivPodomoro, UnivDianNusantara, 1.6);
        WG.addEdge(UnivPodomoro, MallCiputra, 2.3);
        WG.addEdge(MallCiputra, UnivPodomoro, 3.3);
        WG.addEdge(UnivPodomoro, MallTamanAnggrek, 0.65);
        WG.addEdge(MallTamanAnggrek, UnivPodomoro, 0.65);
        WG.addEdge(MallTamanAnggrek, UnivEsaUnggul, 2.5);
        WG.addEdge(UnivEsaUnggul, MallTamanAnggrek, 2.4);
        WG.addEdge(UnivEsaUnggul, UnivBinus, 3.2);
        WG.addEdge(UnivBinus, UnivEsaUnggul, 3.0);
        WG.addEdge(UnivBinus, UnivPertamina, 5.5);
        WG.addEdge(UnivPertamina, UnivBinus, 5.3);
        WG.addEdge(UnivPertamina, RsPelni, 5.7);
        WG.addEdge(RsPelni, UnivPertamina, 5.8);
        WG.addEdge(RsPelni, RsHarapanKita, 3.8);
        WG.addEdge(RsHarapanKita, RsPelni, 2.5);
        WG.addEdge(RsHarapanKita, MallTamanAnggrek, 5.0);
        WG.addEdge(MallTamanAnggrek, RsHarapanKita, 3.9);
        WG.addEdge(RsPelni, RsTniDrMintohardjo, 3.4);
        WG.addEdge(RsTniDrMintohardjo, RsPelni, 3.6);
        WG.addEdge(RsTniDrMintohardjo, GrandIndonesia, 3.6);
        WG.addEdge(GrandIndonesia, RsTniDrMintohardjo, 4.0);
        WG.addEdge(GrandIndonesia, FPsikologUnj, 3.0);
        WG.addEdge(FPsikologUnj, GrandIndonesia, 2.6);
        WG.addEdge(FPsikologUnj, RsAgung, 1.9);
        WG.addEdge(RsAgung, FPsikologUnj, 1.5);
        WG.addEdge(RsAgung, Kasablanka, 2.7);
        WG.addEdge(Kasablanka, RsAgung, 2.3);
        WG.addEdge(Kasablanka, Kuningan, 3.3);
        WG.addEdge(Kuningan, Kasablanka, 1.5);
        WG.addEdge(Kuningan, FPsikologUnj, 4.0);
        WG.addEdge(FPsikologUnj, Kuningan, 3.7);
        WG.addEdge(Kuningan, LotteMall, 1.5);
        WG.addEdge(LotteMall, Kuningan, 1.5);

        WG.addEdge(PasificPlace, AlAzhar, 2.2);
        WG.addEdge(AlAzhar, PasificPlace, 3.2);
        WG.addEdge(AlAzhar, UnivPertamina, 4.3);
        WG.addEdge(UnivPertamina, AlAzhar, 2.8);
        WG.addEdge(UnivPertamina, UnivDarunnajah, 5.6);
        WG.addEdge(UnivDarunnajah, UnivPertamina, 3.4);
        WG.addEdge(UnivDarunnajah, UnivBudiLuhur, 4.4);
        WG.addEdge(UnivBudiLuhur, UnivDarunnajah, 2.2);
        WG.addEdge(UnivBudiLuhur, UnivMercuBuana, 4.7);
        WG.addEdge(UnivMercuBuana, UnivBudiLuhur, 4.6);
        WG.addEdge(UnivMercuBuana, RsudKembangan, 2.9);
        WG.addEdge(RsudKembangan, UnivMercuBuana, 2.2);
        WG.addEdge(RsudKembangan, RsSiloamKebonJeruk, 4.6);
        WG.addEdge(RsSiloamKebonJeruk, RsudKembangan, 3.6);
        WG.addEdge(RsudKembangan, PuriIndahMall, 3);
        WG.addEdge(PuriIndahMall, RsudKembangan, 3);
        WG.addEdge(UnivDarunnajah, GandariaCity, 3.4);
        WG.addEdge(GandariaCity, UnivDarunnajah, 4.6);
        WG.addEdge(GandariaCity, PondokIndah, 3.7);
        WG.addEdge(PondokIndah, GandariaCity, 2.7);
        WG.addEdge(PondokIndah, RsPondokIndah, 4.0);
        WG.addEdge(RsPondokIndah, PondokIndah, 2.1);
        WG.addEdge(RsPondokIndah, SiloamHospitalSimatupang, 4.0);
        WG.addEdge(SiloamHospitalSimatupang, RsPondokIndah, 1.8);
        WG.addEdge(SiloamHospitalSimatupang, UnivBudiLuhur, 11);
        WG.addEdge(UnivBudiLuhur, SiloamHospitalSimatupang, 8.8);
        WG.addEdge(AlAzhar, BlokMPlaza, 1.2);
        WG.addEdge(BlokMPlaza, AlAzhar, 1.0);
        WG.addEdge(BlokMPlaza, UnivDrHamka, 0.9);
        WG.addEdge(UnivDrHamka, BlokMPlaza, 0.9);
        WG.addEdge(UnivDrHamka, GandariaCity, 1.5);
        WG.addEdge(GandariaCity, UnivDrHamka, 1.3);
        WG.addEdge(BlokMPlaza, PondokIndah, 3.6);
        WG.addEdge(PondokIndah, BlokMPlaza, 3.9);
        WG.addEdge(AlAzhar, UnivMhThamrin, 12.2);
        WG.addEdge(UnivMhThamrin, AlAzhar, 11.4);
        WG.addEdge(UnivMhThamrin, BlokMPlaza, 11.4);
        WG.addEdge(BlokMPlaza, UnivMhThamrin, 11.5);
        WG.addEdge(UnivMhThamrin, RsTibet, 7.1);
        WG.addEdge(RsTibet, UnivMhThamrin, 9.1);
        WG.addEdge(RsTibet, Kuningan, 5.5);
        WG.addEdge(Kuningan, RsTibet, 5.5);
        WG.addEdge(Kasablanka, RsTibet, 4.1);
        WG.addEdge(RsTibet, Kasablanka, 4.4);
        WG.addEdge(UnivMputantular, Kasablanka, 5.9);
        WG.addEdge(Kasablanka, UnivMputantular, 5.0);
        WG.addEdge(UnivNahdlatulUlama, UnivMputantular, 5.7);
        WG.addEdge(UnivMputantular, UnivNahdlatulUlama, 5.7);
        WG.addEdge(UnivNahdlatulUlama, RsAgung, 1.1);
        WG.addEdge(RsAgung, UnivNahdlatulUlama, 1.3);
        WG.addEdge(UnivNegeriJakarta, UnivMputantular, 3.9);
        WG.addEdge(UnivMputantular, UnivNegeriJakarta, 5.7);
        WG.addEdge(UnivNegeriJakarta, RsPusatPersahabatan, 1.5);
        WG.addEdge(RsPusatPersahabatan, UnivNegeriJakarta, 1.2);
        WG.addEdge(RsPusatPersahabatan, UnivMputantular, 6.0);
        WG.addEdge(UnivMputantular, RsPusatPersahabatan, 4.0);
        WG.addEdge(RsPusatPersahabatan, PlazaBuaran, 7.2);
        WG.addEdge(PlazaBuaran, RsPusatPersahabatan, 6.8);
        WG.addEdge(PlazaBuaran, MallBasura, 7.2);
        WG.addEdge(MallBasura, PlazaBuaran, 8.2);
        WG.addEdge(MallBasura, UnivMputantular, 0.55);
        WG.addEdge(UnivMputantular, MallBasura, 0.55);
        WG.addEdge(PlazaBuaran, RsIslamJakarta, 11.2);
        WG.addEdge(RsIslamJakarta, PlazaBuaran, 12.1);
        WG.addEdge(MallBasura, MallCipinangJakarta, 5.2);
        WG.addEdge(MallCipinangJakarta, MallBasura, 5.4);
        WG.addEdge(MallCipinangJakarta, UnivKristenIndonesai, 3.8);
        WG.addEdge(UnivKristenIndonesai, MallCipinangJakarta, 3.0);
        WG.addEdge(UnivKristenIndonesai, MallBasura, 4.6);
        WG.addEdge(MallBasura, UnivKristenIndonesai, 5.7);
        WG.addEdge(MallCipinangJakarta, UnivBorobudur, 0.85);
        WG.addEdge(UnivBorobudur, MallCipinangJakarta, 0.85);
        WG.addEdge(UnivBorobudur, UnivNusaMandiri, 4.1);
        WG.addEdge(UnivNusaMandiri, UnivBorobudur, 1.1);
        WG.addEdge(UnivNusaMandiri, PondokKelapaTownSquare, 5.7);
        WG.addEdge(PondokKelapaTownSquare, UnivNusaMandiri, 5.1);
        WG.addEdge(UnivKristenIndonesai, UnivDirgantara, 5.4);
        WG.addEdge(UnivDirgantara, UnivKristenIndonesai, 3.4);
        WG.addEdge(UnivDirgantara, RsAngkatanUdara, 0.8);
        WG.addEdge(RsAngkatanUdara, UnivDirgantara, 0.8);
        WG.addEdge(UnivDirgantara, RsBhayangkara, 3.0);
        WG.addEdge(RsBhayangkara, UnivDirgantara, 8.3);
        WG.addEdge(RsBhayangkara, UnivKristenIndonesai, 2.7);
        WG.addEdge(UnivKristenIndonesai, RsBhayangkara, 3.2);
        WG.addEdge(LippoPlazaKeramatJati, RsBhayangkara, 0.4);
        WG.addEdge(RsBhayangkara, LippoPlazaKeramatJati, 0.4);
        WG.addEdge(UnivKristenIndonesai, LippoPlazaKeramatJati, 3.2);
        WG.addEdge(LippoPlazaKeramatJati, UnivKristenIndonesai, 2.5);
        WG.addEdge(RsBhayangkara, UnivBinawan, 2.2);
        WG.addEdge(UnivBinawan, RsBhayangkara, 2.0);
        WG.addEdge(UnivBinawan, LippoPlazaKeramatJati, 1.7);
        WG.addEdge(LippoPlazaKeramatJati, UnivBinawan, 2.2);
        WG.addEdge(PlazaKalibata, UnivBinawan, 2.0);
        WG.addEdge(UnivBinawan, PlazaKalibata, 1.1);
        WG.addEdge(UnivTrilogi, PlazaKalibata, 1.4);
        WG.addEdge(PlazaKalibata, UnivTrilogi, 2.1);
        WG.addEdge(UnivLia, UnivTrilogi, 1.7);
        WG.addEdge(UnivTrilogi, UnivLia, 1.6);
        WG.addEdge(RsTibet, UnivLia, 4.7);
        WG.addEdge(UnivLia, RsTibet, 3.5);
        WG.addEdge(RsTibet, UnivKristenIndonesai, 3.6);
        WG.addEdge(UnivKristenIndonesai, RsTibet, 4.5);
        WG.addEdge(RsTriaDipa, RsTibet, 1.7);
        WG.addEdge(RsTibet, RsTriaDipa, 4.4);
        WG.addEdge(UnivMhThamrin, RsTriaDipa, 9.0);
        WG.addEdge(RsTriaDipa, UnivMhThamrin, 8.4);
        WG.addEdge(PlazaAdorama, UnivMhThamrin, 12.4);
        WG.addEdge(UnivMhThamrin, PlazaAdorama, 11.4);
        WG.addEdge(LippoMallKemang, PlazaAdorama, 0.8);
        WG.addEdge(PlazaAdorama, LippoMallKemang, 0.8);
        WG.addEdge(PondokIndah, LippoMallKemang, 5.8);
        WG.addEdge(LippoMallKemang, PondokIndah, 5.3);
        WG.addEdge(CiladakTownSquare, BlokMPlaza, 7.4);
        WG.addEdge(BlokMPlaza, CiladakTownSquare, 7.0);
        WG.addEdge(SiloamHospitalSimatupang, CiladakTownSquare, 3.2);
        WG.addEdge(CiladakTownSquare, SiloamHospitalSimatupang, 3.0);
        WG.addEdge(LippoMallKemang, UnivTrilogi, 5.6);
        WG.addEdge(UnivTrilogi, LippoMallKemang, 6.8);
        WG.addEdge(UnivTrilogi, RsTriaDipa, 2.8);
        WG.addEdge(RsTriaDipa, UnivTrilogi, 2.5);
        WG.addEdge(CiladakTownSquare, TransmartCiladak, 4.5);
        WG.addEdge(TransmartCiladak, CiladakTownSquare, 3.8);
        WG.addEdge(TransmartCiladak, LippoMallKemang, 5.5);
        WG.addEdge(LippoMallKemang, TransmartCiladak, 7.2);
        WG.addEdge(AeonMall, TransmartCiladak, 0.85);
        WG.addEdge(TransmartCiladak, AeonMall, 0.85);
        WG.addEdge(CiladakTownSquare, AeonMall, 4.0);
        WG.addEdge(AeonMall, CiladakTownSquare, 4.7);
        WG.addEdge(AeonMall, PlazaKalibata, 10.3);
        WG.addEdge(PlazaKalibata, AeonMall, 6.2);
        WG.addEdge(UnivPancasila, AeonMall, 5.8);
        WG.addEdge(AeonMall, UnivPancasila, 4.9);
        WG.addEdge(AeonMall, RsAdhyaksa, 11.3);
        WG.addEdge(RsAdhyaksa, AeonMall, 6.7);
        WG.addEdge(RsAdhyaksa, LippoPlazaKeramatJati, 6.1);
        WG.addEdge(LippoPlazaKeramatJati, RsAdhyaksa, 7.1);
        WG.addEdge(LippoPlazaKeramatJati, RsBinawaluya, 4.9);
        WG.addEdge(RsBinawaluya, LippoPlazaKeramatJati, 5.0);
        WG.addEdge(RsBinawaluya, RsAdhyaksa, 4.0);
        WG.addEdge(RsAdhyaksa, RsBinawaluya, 3.9);
        WG.addEdge(UnivAtmaJaya, PasificPlace, 1.2);
        WG.addEdge(PasificPlace, UnivAtmaJaya, 2.5);
        WG.addEdge(UnivAtmaJaya, LotteMall, 3.2);
        WG.addEdge(LotteMall, UnivAtmaJaya, 1.3);
        WG.addEdge(UnivAtmaJaya, FPsikologUnj, 4.5);
        WG.addEdge(FPsikologUnj, UnivAtmaJaya, 3.3);
        WG.addEdge(UnivAtmaJaya, RsTniDrMintohardjo, 2.1);
        WG.addEdge(RsTniDrMintohardjo, UnivAtmaJaya, 2.2);

        // Print laptop specifications
        System.out.println("Laptop Specifications:");
        System.out.println("Operating System: " + System.getProperty("os.name"));
        System.out.println("OS Version: " + System.getProperty("os.version"));
        System.out.println("Architecture: " + System.getProperty("os.arch"));
        System.out.println("Java Version: " + System.getProperty("java.version"));

        // Start timing the program execution
        long startTime = System.currentTimeMillis();


        System.out.println("\nDijkstra: ");
        //masukkan parameter 1 sebagai node awal dan parameter 2 sebagai node tujuanya
        WG.dijkstra(UnivAtmaJaya,GandariaCity);

        // End timing the program execution
        long endTime = System.currentTimeMillis();
        long executionTime = endTime - startTime;
        System.out.println("\nExecution Time: " + executionTime + " milliseconds");
    }
}